# Generated by Django 5.0 on 2023-12-07 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_tecaher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tecaher',
            new_name='Teacher',
        ),
    ]
